server:
  port: 8080
http:
  proxy:
    enable: true
    host: 192.168.3.31
    port: 8888
saas:
  auth:
    path: auth
    fileName: public_70aa39752b0b4a069bd9db77005d51c2.key
  service:
    url: http://api.longdundata.com/service
    uid: 70aa39752b0b4a069bd9db77005d51c2